sudo: required
dist: trusty
group: edge
language: c

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - autogen
            - libogg-dev
            - libvorbis-dev
            - libflac-dev
            - libasound2-dev
            - pkgconf
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - autogen
            - libogg-dev
            - libvorbis-dev
            - libflac-dev
            - libasound2-dev
            - pkgconf

    - os: osx
      compiler: clang

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update
      brew install autogen flac libogg libvorbis pkgconf
    fi

install:
  - true

script:
  - mkdir cmake-build && (cd cmake-build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-Wall -Wextra" && make VERBOSE=1 && ctest -V)
  - pwd
  - ./autogen.sh
  - ./configure --enable-werror && make clean all check && make distcheck
