group: travis_latest
sudo: required
language: c

matrix:
  include:
    - os: linux
      dist: xenial
      compiler:
        - clang
        - gcc
      addons:
        apt:
          packages:
            - autogen
            - libogg-dev
            - libvorbis-dev
            - libflac-dev
            - libasound2-dev
    - os: osx
      compiler: clang

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update
      brew install autogen flac libogg libvorbis
    fi

install:
  - true

script:
  - mkdir cmake-build && (cd cmake-build && cmake .. -DCMAKE_BUILD_TYPE=Release && make VERBOSE=1 && ctest -V)
  - pwd
  - ./autogen.sh
  - ./configure --enable-werror && make clean all check && make distcheck
