sudo: required
language: c
matrix:
  include:
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          packages:
            - autogen
            - libogg-dev
            - libvorbis-dev
            - libflac-dev
            - libasound2-dev
      env:
        - BUILD_TOOL=autotools
        - BUILD_TOOL=cmake
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - autogen
            - libogg-dev
            - libvorbis-dev
            - libflac-dev
            - libasound2-dev
      env:
        - BUILD_TOOL=autotools
        - BUILD_TOOL=cmake
    - os: osx
      compiler: clang
      env:
        - BUILD_TOOL=autotools
        - BUILD_TOOL=cmake

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update
      brew install autogen flac libogg libvorbis
    fi

install:
  - true

script:
  - if [[ "${BUILD_TOOL}" == "cmake" ]]; then mkdir cmake-build && (cd cmake-build && cmake .. -DCMAKE_BUILD_TYPE=Release && make VERBOSE=1 && ctest -V); fi
  - if [[ "${BUILD_TOOL}" == "autotools" ]]; then /autogen.sh && ./configure --enable-werror && make clean all check && make distcheck; fi
