group: travis_latest
sudo: required
language: c
env:
  include:
    - BUILD_SYSTEM=Autotools
    - BUILD_SYSTEM=CMake
os:
  - linux
  - osx
dist: xenial
compiler:
  - gcc
  - clang
env:
  - BUILD_SYSTEM=Autotools
  - BUILD_SYSTEM=CMake
addons:
  apt:
    packages:
      - autogen
      - libogg-dev
      - libvorbis-dev
      - libflac-dev
      - libasound2-dev
      - ninja-build
matrix:
  exclude:
    - os: osx
      compiler: clang

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update
      brew install autogen flac libogg libvorbis ninja
    fi

install:
  - true

script:
  - if [[ "${BUILD_SYSTEM}" == "CMake" ]]; then mkdir cmake-build && (cd cmake-build && cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS:STRING="-Werror" && cmake --build . && ctest --output-on-failure); fi
  - if [[ "${BUILD_SYSTEM}" == "Autotools" ]]; then ./autogen.sh && ./configure --enable-werror && make clean all check && make distcheck; fi
