dist: travis_latest
group: edge
sudo: required
language: c

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          packages:
            - autogen
            - libogg-dev
            - libvorbis-dev
            - libflac-dev
            - libasound2-dev
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - autogen
            - libogg-dev
            - libvorbis-dev
            - libflac-dev
            - libasound2-dev

    - os: osx
      compiler: clang

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update
      brew install autogen flac libogg libvorbis
    fi

install:
  - true

script:
  - pwd
  - ./autogen.sh
  - ./configure --enable-werror && make clean all check && make distcheck
