group: travis_latest
sudo: required
language: c
env:
  include:
    - BUILD_TOOL=autotools
    - BUILD_TOOL=cmake
os:
  - linux
  - osx
dist: xenial
compiler:
  - gcc
  - clang
env:
  - BUILD_TOOL=autotools
  - BUILD_TOOL=cmake
addons:
  apt:
    packages:
      - autogen
      - libogg-dev
      - libvorbis-dev
      - libflac-dev
      - libasound2-dev
matrix:
  exclude:
    - os: osx
      compiler: clang

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update
      brew install autogen flac libogg libvorbis
    fi

install:
  - true

script:
  - if [[ "${BUILD_TOOL}" == "cmake" ]]; then mkdir cmake-build && (cd cmake-build && cmake .. -DCMAKE_BUILD_TYPE=Release && make VERBOSE=1 && ctest -V); fi
  - if [[ "${BUILD_TOOL}" == "autotools" ]]; then ./autogen.sh && ./configure --enable-werror && make clean all check && make distcheck; fi
