version: 1.0.29pre1-{build}
image: Visual Studio 2017
configuration: Debug
platform:
  - Win32
  - x64
install:
  - pip3 install conan
before_build:
  - mkdir CMakeBuild
  - cd CMakeBuild
  - conan install ..
  - if %platform%==Win32 set CMAKE_GENERATOR=Visual Studio 15 2017
  - if %platform%==x64 set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
  - cmake .. -G"%CMAKE_GENERATOR%"
build:
  project: c:\projects\libsndfile\CMakeBuild\libsndfile.sln
  verbosity: minimal
test_script:
  - ctest -V
cache:
  C:\Tools\vcpkg\Installed -> appveyor.yml
