jobs:
  - job: Ubuntu_CMake
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: |
        sudo apt-get install -y autogen libogg-dev libvorbis-dev libflac-dev libasound2-dev libsqlite3-dev libspeex-dev
      displayName: Installing dependencies
    - script: |
        mkdir build
      displayName: Creating build directory
    - task: CMake@1
      inputs:
        workingDirectory: 'build'
        cmakeArgs: ' ..'
    - script: |
        cd build
        cmake --build .
      displayName: Building
    - script: |
        cd build
        ctest
      displayName: Testing
  - job: Windows_CMake_VS2017_Win32
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: git clone https://github.com/microsoft/vcpkg
      displayName: Bootstraping Vcpkg
    - script: .\vcpkg\bootstrap-vcpkg.bat
      displayName: Bootstraping Vcpkg
    - script: .\vcpkg\vcpkg.exe install libogg libvorbis libflac sqlite3 speex
      displayName: Installing dependencies
    - script: |
        mkdir build
      displayName: Creating build directory
    - task: CMake@1
      inputs:
        workingDirectory: 'build'
        cmakeArgs: ' -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake ..'
    - script: |
        cd build
        cmake --build .
      displayName: Building
    - script: |
        cd build
        ctest
      displayName: Testing
